version: "3.8"
services:
  firstsilo:
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    build:  
      context: .
      dockerfile: ./ops/SiloHost/Dockerfile
      network: host
    environment:
    - GATEWAYPORT=3001
    - SILOPORT=2001
    - ADVERTISEDIP=172.28.1.1
    ports:
      - "3005:8080"
      
  secondsilo:
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    build:  
      context: .
      dockerfile: ./ops/SiloHost/Dockerfile
    environment:
    - GATEWAYPORT=3002
    - ADVERTISEDIP=172.28.1.2
    - SILOPORT=2002
    - PEERPORT=2001
    - PEERADDRESS=172.28.1.1
  siloclient:
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    build:  
      context: .
      dockerfile: ./ops/Client/Dockerfile
    environment:
    - SILOGATEWAYS=172.28.1.1:3001,172.28.1.2:3002
  siloclient2:
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
    build:  
      context: .
      dockerfile: ./ops/Client/Dockerfile
    environment:
    - SILOGATEWAYS=172.28.1.1:3001,172.28.1.2:3002
networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16