version: "3.8"
services:
  primarysilo:
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    build:  
      context: .
      dockerfile: ./ops/SiloHost/Dockerfile
      network: host
    environment:
    - GATEWAYPORT=3001
    - SILOPORT=2000
    ports:
      - "3005:8080"
  secondarysilo:
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    build:  
      context: .
      dockerfile: ./ops/SiloHost/Dockerfile
      network: host
    environment:
    - GATEWAYPORT=3002
    - SILOPORT=2001
    - PRIMARYSILOPORT=2000
    - PRIMARYSILOADDRESS=172.28.1.1
  siloclient:
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    build:  
      context: .
      dockerfile: ./ops/Client/Dockerfile
    environment:
    - GATEWAYPORT=3001
    - SILODOMAIN=172.28.1.1
  siloclient2:
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
    build:  
      context: .
      dockerfile: ./ops/Client/Dockerfile
    environment:
    - GATEWAYPORT=3002
    - SILODOMAIN=172.28.1.2
networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16