@startuml
hide empty description
  state "road to orleans" as PhaseA{
    state "solution 1" as Solution1{
      Solution1 : One basic silo, no grains.
    }

    state "solution 2" as Solution2{
      Solution2 : One basic silo, one grain, one console client.
    }

    state "solution 3" as Solution3{
      Solution3 : One basic silo, one grain,
      Solution3 : one console client,
      Solution3 : everything containerized.
    }

    state "solution 3a" as Solution3a{
      Solution3a : Solution3 + grain persistence.
    }

    state "solution 3b" as Solution3b{
      Solution3b : Solution3 + datadog APM.
    }

    state "solution 4" as Solution4{
      Solution4 : First in-memory clustering example.
      Solution4 : Many silos, many clients.
    }

    state "solution 5" as Solution5{
      Solution5 : Solution4 where the grain interfaces F# library code.
      Solution5 : Additionally, F# unit tests covering the F# library code.
    }

    state "solution 6" as Solution6{
      Solution6 : Solution5 where the cluster is being called from a Web API.
    }

    state "solution 7" as Solution7{
      Solution7 : Solution6 + FeatureManagement,
      Solution7 : dependency injection in grains,
      Solution7 : unit tests for grains using OrleansTestKit.ß
    }

    state "solution 8" as Solution8{
      Solution8 : Solution7 + Persistent Membership Table in DynamoEB,
      Solution8 : ECS hosting, CloudFormation Template.
    }

    [*] --> Solution1
    Solution1 --> Solution2
    Solution2 --> Solution3
    Solution3 --> Solution3a
    Solution3 --> Solution3b
    Solution3 --> Solution4
    Solution4 --> Solution5
    Solution5 --> Solution6
    Solution6 --> Solution7
    Solution7 --> Solution8
    Solution8 --> [*]
  }
@enduml