#!/bin/bash

ADVERTISEDIP="192.168.0.66"
PRIMARYSILOPORT=2001
SILOPORT=2001
GATEWAYPORT=3001
DASHBOARDPORT=8081

docker build -t silo-host -f ./ops/Dockerfile ./ &&
  docker run -it -e SILOPORT=$SILOPORT -e GATEWAYPORT=$GATEWAYPORT -e ADVERTISEDIP=$ADVERTISEDIP -e PRIMARYSILOPORT=$PRIMARYSILOPORT -p $SILOPORT:2000 -p $GATEWAYPORT:3000 -p $DASHBOARDPORT:8080 --rm silo-host
