name: Solution2 Build

on:
  push:
  pull_request:
    branches:
          - solution2

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-build --verbosity normal 