name: Solution4 Build

on:  
  push:
  pull_request:
    branches: 
          - solution4

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore  
    - name: Build
      run: dotnet build --no-restore