name: Solution7 Build

on:  
  pull_request:
    branches: 
          - main 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore  
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal