name: Solution7 Build

on:
  push:
  pull_request:
    branches: 
          - solution7 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore  
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal